<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.79.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" Version="1.79.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.79.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Ragume.Data/Ragume.Data.csproj" />
    <ProjectReference Include="../Ragume.KernelFactory/Ragume.KernelFactory.csproj" />
  </ItemGroup>

</Project>
